### ISSUE TITLE
Error during Batch Analysis

### ISSUE THREAD

**Issue by rainacao** [DeNardoLab/BehaviorDEPOT#15]
Hello,

I'm getting an error when I attempt to run batch analysis on some data.

Here is what the error message looks like:
![image](https://github.com/DeNardoLab/BehaviorDEPOT/assets/45450525/19c60eb9-6d2c-4b8e-9837-5f567b9a1157)

It seems to be an issue with reuse_roi_names, which I tried to comment out in the makeParamsStruct.m code, but any changes are not preserved when I run the application.

Is there any way to resolve this?

**Comment by rainacao** [comment]
We are not looking at any ROIs, so the roi variables are not necessary for us, and we have set # of ROIs in spatial filtering to 0. We are only running the calculateFreezing_velocity classifier as well.

**Comment by cjgabrie** [comment]
Hi! Thanks for trying out BehaviorDEPOT!

The error you encountered is due to a bug introduced in a recent feature update. I got rid of the bug and updated the code to v1.51 with the fix. You should be able to simply download the new .mlappinstall file and update your version to fix the issue.
