### ISSUE TITLE
Issues installing BehaviorDEPOT v1.51

### ISSUE THREAD

**Issue by NataliaFavila** [DeNardoLab/BehaviorDEPOT#16]
Dear team,

after downloading the repository and running the .mlappinstall file I get the following error when trying to launch BehaviorDEPOT from App window in Matlab (version 2020a): 

Unrecognized property 'WordWrap' for class 'matlab.ui.control.CheckBox'.
Error in BehaviorDEPOT_GUI_v1_5/createComponents (line 765)
            app.ApplyHampelCorrectionCheckBox.WordWrap = 'on';
Error in BehaviorDEPOT_GUI_v1_5 (line 1041)
            createComponents(app)
Error in BehaviorDEPOTv151App/startApp (line 86)
                obj.AppHandle = eval('BehaviorDEPOT_GUI_v1_5');
Error in BehaviorDEPOTv151App (line 48)
            startApp(obj)
Error in appinstall.internal.runapp>execute (line 116)
out = evalin('caller', [script ';']);
Error in appinstall.internal.runapp>runapp13a (line 95)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));
Error in appinstall.internal.runapp>preamble18b (line 60)
    appobj = runapp13a(appinstalldir);
Error in appinstall.internal.runapp (line 13)
    out = preamble18b(appinstalldir);
Error in matlab.apputil.run (line 45)
appinstall.internal.runapp(appName, appLocation); 

Any suggestions or ideas why this might be happening?
Thank you!
Natalia

**Comment by cjgabrie** [comment]
Oh--if you haven't done so, could you try simply un-installing the app in Matlab and then re-installing?
