### ISSUE TITLE
BehaviorDepot

### ISSUE THREAD

**Issue by Maroca5** [DeNardoLab/BehaviorDEPOT#18]
Hello I'm getting an error at the time of calibration is saying duplicate file and it doesn't proceed.

**Comment by cjgabrie** [comment]
Hello! Thanks for trying out BehaviorDEPOT. Can you post the error you are receiving? Ideally, you can copy the MATLAB error message stack and attach as a text file or image. I'd be happy to help you figure out what's going on.

**Comment by Maroca5** [comment]
Warning: Name is nonexistent or not a directory: D:\JP Calibration Testing 
Error using cell2struct
Duplicate field name "Exploration"

Error in BehaviorDEPOT_GUI_v1_5/StartButtonPushed (line 419)
            app.P.Params = cell2struct([struct2cell(tempParams); struct2cell(editParams)], names, 1);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

>>

**Comment by Maroca5** [comment]
Hello, have you had a chance to look at the error code?
________________________________
From: cjgabrie ***@***.***>
Sent: Wednesday, February 7, 2024 12:31 PM
To: DeNardoLab/BehaviorDEPOT ***@***.***>
Cc: Maria Carrasco ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DeNardoLab/BehaviorDEPOT] BehaviorDepot (Issue #18)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Hello! Thanks for trying out BehaviorDEPOT. Can you post the error you are receiving? Ideally, you can copy the MATLAB error message stack and attach as a text file or image. I'd be happy to help you figure out what's going on.

**Comment by Maroca5** [comment]
Error using cell2struct
Duplicate field name "Freezing"

Error in BehaviorDEPOT_GUI_v1_5/StartButtonPushed (line 419)
            app.P.Params = cell2struct([struct2cell(tempParams); struct2cell(editParams)], names, 1);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

>>

**Comment by cjgabrie** [comment]
Hi,

Apologies for the delay in figuring this out. I'm currently focusing on wrapping up my dissertation and will be active again soon. This is difficult to figure out just from the error code--what I can tell is that you are getting duplicate parameter fields for certain classifiers (exploration and freezing). This is not behavior I have seen in other cases. Would you let me know a bit more about your situation--e.g. what classifiers are you trying, do you always get this message, etc.? I'd be happy to look more closely at your situation to figure out what's going wrong.
