### ISSUE TITLE
Inquiry regarding point alignment after inputting video file and tracking file

### ISSUE THREAD

**Issue by ScienceBI** [DeNardoLab/BehaviorDEPOT#19]
Hello. I am a first-time user of behaviorDEPOT with very limited coding experience. 
I encountered an issue while using BehaviorDEPOT and would like to inquire about it. Specifically, I have questions regarding the alignment problem of body parts when inputting tracking files and video files.
As a result of my analysis, I noticed that multiple points are detected for each body part, leading to outcomes that differ from my expectations. I am curious about the root cause of this discrepancy and seek guidance on how to address it.
![figure1](https://github.com/DeNardoLab/BehaviorDEPOT/assets/161629405/eaae7537-21d2-4124-a17b-da898e50f59a)

**Comment by RutdelaVega** [comment]
Hello! I have the same issue. In my case, it looks like is taking 4 frames and overlapping the tracking points in the same figure together with a random image from the video. In my case, it doesn't seem to affect posterior analysis of freezing behavior, but just to be sure that is working properly. This happens even if I do single animal processing. Thank you for your help!
![Captura de pantalla 2024-03-21 094152](https://github.com/DeNardoLab/BehaviorDEPOT/assets/122618780/f6d06c98-ce1e-4549-96fa-df3746eda2f0)

**Comment by cjgabrie** [comment]
This issue has been resolved in v1.6, now available!
