### ISSUE TITLE
Error selecting multiple ROIs

### ISSUE THREAD

**Issue by Vizent-T** [DeNardoLab/BehaviorDEPOT#20]
I indicated more than 1 ROI in the GUI. However, there is an error when selecting more than 1 ROI. I can outline the 1st ROI fine, but there is an error afterward with no option to select another ROI. Here is the output from matplot:

Select tracking file
Select video file
Loading video. May take some time depending on size of video.
Video Loaded
Select ROI # 1
Select ROI # 2
Unrecognized field name "roi_limits".

Error in drawROIs (line 23)
                       plot(polyshape(P.roi_limits{nroi}),
                       'FaceAlpha', 0.25)

Error in BD_dataPrep (line 14)
P = drawROIs(Frame, P);

Error in BehDEPOT_mainscript (line 29)
        [Params, Tracking, Metrics, P] = BD_dataPrep(P, j);

Error in BehaviorDEPOT_GUI_v1_5/StartButtonPushed (line 422)
            BehDEPOT_mainscript(app.P)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

Thank you for helping!

**Comment by cjgabrie** [comment]
This issue has been resolved in v1.6, now available!
