### ISSUE TITLE
Tracking File

### ISSUE THREAD

**Issue by devin417** [DeNardoLab/BehaviorDEPOT#4]
Hello,
matlab prompts me to upload a tracking file before uploading the video file. What file is it referring to ?

**Comment by cjgabrie** [comment]
Hello--

The tracking file is the keypoint tracking info obtained using DeepLabCut or equivalent software. Right now, you can use a CSV or H5 format. 

See Inputs page in wiki for more info: https://github.com/DeNardoLab/BehaviorDEPOT/wiki/Inputs
