### ISSUE TITLE
Matlab error and tracking file body part labeling question

### ISSUE THREAD

**Issue by devin417** [DeNardoLab/BehaviorDEPOT#5]
Sorry to bug you again. I am getting an error in Matlab. I created a .csv tracking file, but I am unclear if there are specific body parts I need to label for my file to work with your program? The error I got is:

Argument to dynamic structure reference must evaluate to a valid
field name.

Error in genTracking_custom (line 20)
        Tracking.Raw.(this_part) = data(i*3-1:i*3+1,:);

Error in BehDEPOT_mainscript (line 109)
    Tracking = genTracking_custom(data, Params);

Error in BehaviorDEPOT_GUI_v1_2/StartButtonPushed (line 386)
            BehDEPOT_mainscript(app.P)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.

Thanks so much for your help/patience.

**Comment by cjgabrie** [comment]
Hmm...this could be an issue with the CSV. Have you run the demo data
successfully? I think one of the easiest things I could suggest is to look
at demo tracking data to evaluate if your CSV is correctly formatted.

When BehaviorDEPOT scans the tracking CSV, it simply pulls out the data and
the names already labeled and then prompts you to register each part with
those known by the program.

**Comment by devin417** [comment]
It appears to be the same but I have attached the .csv file below. Forgive my ignorance, I have spent years only working on Matlab and so this is my first venture into Python/DeepLabCut. 

[CollectedData_Devin.csv](https://github.com/DeNardoLab/BehaviorDEPOT/files/8550503/CollectedData_Devin.csv)

**Comment by cjgabrie** [comment]
I checked out your CSV and it's the not formatted the same as a tracking file. The blank columns you added are throwing things off as well as the fact that you don't include a frame index associated with the tracking data. You should have a tracked frame for each frame of the video you want to analyze. If you want to simulate the data, you should simulate a value for each frame in the video (or trim the frames in the video). BehaviorDEPOT figures out the total number of frames based on the frame index for tracked values. 

See the demo data CSVs for other examples of formatting.

**Comment by devin417** [comment]
OK I am going to check out your CSV files. At what point in DLC do you make this tracking file? I am wondering if I am not choosing the correct parameters when I am training/labeling frames. I definitely am not labeling every single frame of the entire video. I am sorry again to bug you on this. I know you're busy and probably have a lot of other things to do with your time.

**Comment by cjgabrie** [comment]
No problem. 

You can look at the DLC GitHub page for extensive documentation on all functions and workflow for DLC.

In brief, you make a DLC project, label a subset of frames, train the network, and then use the trained network to generate the tracking information for each part you choose (a minimum of nose, ears, and tailbase for BehaviorDEPOT) per video session.

**Comment by cjgabrie** [comment]
No problem.

You can look at the DLC GitHub page for extensive documentation on all
functions and workflow for DLC.

In brief, you make a DLC project, label a subset of frames, train the
network, and then use the trained network to generate the tracking
information for each part you choose (a minimum of nose, ears, and tailbase
for BehaviorDEPOT) per video session.
